config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: "order#index"
    resources :items, only: [:new, :create, :index, :edit, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index]
    resources :order_details, only: [:show]
  end

  namespace :public do
    root to: "homes#top"
    get 'home/about' => "homes#about",as: 'about'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :destory]
    resources :customers, only: [:show, :edit, :update]
    resources :orders, only: [:index]
    resources :order_details, only: [:show]
    get 'shared/links', to: 'shared#links'
  end
  root to: "public/homes#top"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_item

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
  before_action :authenticate_admin!
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(item_params)
      redirect_to admin_customer_path(@customer)
    else
      render :action => "edit"
    end
  end

private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :action => "edit"
    end
  end

private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/controllers/admin/order_details_controller.rb
class Admin::OrderDetailsController < ApplicationController
  def show
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @order = Order.page(params[:page]).per(10)
  end

private

  def order_params
    params.require(:order).permit(:postage, :payment_method, :billing_amount)
  end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
  before_action :authenticate_admin!
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/views/admin/customers/edit.html.erb
<h4>
  <strong><%= @customer.last_name %><%= @customer.first_name %></strong>さんの<strong>会員情報編集</strong>
</h4>
<%= form_with url: admin_customer_path, model: @customer do |f| %>
<table>
  <tr>
    <th>会員ID</th><td><%= @customer.id %></td>
  </tr>
  <tr>
    <th>氏名</th><td><%= f.text_field :last_name %> <%= f.text_field :first_name %></td>
  </tr>
  <tr>
    <th>フリガナ</th><td><%= f.text_field :last_name_kana %> <%= f.text_field :first_name_kana %></td>
  </tr>
  <tr>
    <th>郵便番号</th><td><%= f.text_field :postal_code %></td>
  </tr>
  <tr>
    <th>住所</th><td><%= f.text_field :address %></td>
  </tr>
  <tr>
    <th>電話番号</th><td><%= f.text_field :telephone_number %></td>
  </tr>
  <tr>
    <th>メールアドレス</th><td><%= f.text_field :email %></td>
  </tr>
</table>
<div>
  <%= f.submit '変更を保存' %>
</div>
<% end %>

app/views/admin/customers/index.html.erb
<h4>会員一覧</h4>
  <table>
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
    </tr>
    <% @customers.each do |customer| %>
      <tr>
        <td>
          <%= customer.id %>
        </td>
        <td>
          <%= link_to admin_customer_path(customer.id) do %>
            <%= customer.last_name %><%= customer.first_name %>
          <% end %>
        </td>
        <td>
          <%= customer.email %>
        </td>
      </tr>
      <% end %>
  </table>
  <%= paginate @customers, per_page: 10 %>

app/views/admin/customers/show.html.erb
<h4>
  <strong><%= @customer.last_name %><%= @customer.first_name %></strong>さんの<strong>会員詳細</strong>
</h4>
<table>
  <tr>
    <th>会員ID</th><td><%= @customer.id %></td>
  </tr>
  <tr>
    <th>氏名</th><td><%= @customer.last_name %> <%= @customer.first_name %></td>
  </tr>
  <tr>
    <th>フリガナ</th><td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
  </tr>
  <tr>
    <th>郵便番号</th><td><%= @customer.postal_code %></td>
  </tr>
  <tr>
    <th>住所</th><td><%= @customer.address %></td>
  </tr>
  <tr>
    <th>電話番号</th><td><%= @customer.telephone_number %></td>
  </tr>
  <tr>
    <th>メールアドレス</th><td><%= @customer.email %></td>
  </tr>
</table>
<div>
  <%= link_to edit_admin_customer_path(@customer) do %>
    編集する
  <% end %>
</div>
<div>
  <%= link_to admin_orders_path do %>
    注文履歴一覧を見る
  <% end %>
</div>

app/views/admin/items/edit.html.erb
<h4>商品編集</h4>
<div>商品画像</div>
<%= form_with url: admin_item_path,  model: @item do |f| %>
<div>
  <%= f.file_field :image, accept: "image/*" %>
</div>
<div>商品名</div>
<div>
  <%= f.text_field :name %>
</div>
<div>商品説明</div>
<div>
  <%= f.text_area :introduction %>
</div>
<div>税抜き価格</div>
<div>
  <%= f.text_field :price %>円
</div>
<div>
  <%= f.submit '変更を保存' %>
</div>
<% end %>

app/views/admin/items/index.html.erb
<h4>商品一覧</h4>
<span>
  <a href="/admin/items/new">
  <i class="fa-solid fa-plus"></i>
  </a>
</span>
<table>
  <tr>
    <th>商品ID</th>
    <th>商品名</th>
    <th>税抜き価格</th>
  </tr>
  <% @items.each do |item| %>
    <tr>
      <td>
        <%= item.id %>
      </td>
      <td>
        <%= link_to admin_item_path(item.id) do %>
          <%= item.name %>
        <% end %>
      </td>
      <td>
        <%= item.price %>
      </td>
    </tr>
  <% end %>
</table>
<%= paginate @items, per_page: 10 %>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row no-gutters">
  <h4 class="ml-2 mr-10">商品新規登録</h4>
  <%= form_with url: admin_items_path,  model: @item do |f| %>
  <div class="col-md-3 ml-1 mr-2 px-0 my-3">
    <div>
      <div>商品画像</div>
        <div>
          <%= f.file_field :image, accept: "image/*" %>
        </div>
    </div>
    <div>
      <div>商品名</div>
        <div>
          <%= f.text_field :name %>
        </div>
    </div>
    <div>
      <div>商品説明</div>
        <div>
          <%= f.text_area :introduction %>
        </div>
    </div>
    <div>
      <div>税抜き価格</div>
        <div>
          <%= f.text_field :price %>円
        </div>
    </div>
    <div>
      <%= f.submit '新規登録' %>
    </div>
  </div>
  <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<h4>商品詳細</h4>
<%= image_tag @item.get_image, size: "200x100" %>

<div>
  <div>商品名</div>
  <div>
    <%= @item.name %>
  </div>
  <div>商品説明</div>
  <div>
    <%= @item.introduction %>
  </div>
  <div>税込み価格<br>
  (税抜き価格)</div>
  <div>
    <%= @item.price %>(<%= (@item.price / 1.1).round %>)円
  </div>
  <div>
    <%= link_to edit_admin_item_path(@item) do %>
      編集する
    <% end %>
  </div>
</div>

app/views/admin/order_details/show.html.erb
<h1>show</h1>