config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  namespace :admin do
    root to: "order#index"
    resources :items, only: [:new, :create, :index, :edit, :show, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index]
    resources :order_details, only: [:show]
  end

  namespace :public do
    root to: "homes#top"
    get 'home/about' => "homes#about",as: 'about'
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :destory]
    resources :customers, only: [:show, :edit, :update]
    resources :orders, only: [:index]
    resources :order_details, only: [:show]
    get 'shared/links', to: 'shared#links'
  end
  root to: "public/homes#top"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_item

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(item_params)
      redirect_to admin_customer_path(@customer)
    else
      render :action => "edit"
    end
  end

private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_items_path
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page]).per(10)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render :action => "edit"
    end
  end

private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :image)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def index
    @order = Order.page(params[:page]).per(10)
  end

private

  def order_params
    params.require(:order).permit(:postage, :payment_method, :billing_amount)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
  before_action :authenticate_admin!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/order_helper.rb
module Admin::OrderHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/shared_helper.rb
module SharedHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/f4d3a5e756.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand" href="/public">
            <span>
              LOGO
            </span>
          </a>

          <div>
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li>
                  <%= link_to admin_items_path do %>
                    商品一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_customers_path do %>
                    会員一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_root_path do %>
                    注文履歴一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_admin_session_path, method: :delete do %>
                    ログアウト
                  <% end %>
                </li>

              <% elsif customer_signed_in? %>
                <li>
                  <%= link_to public_customer_path(current_customer) do %>
                    マイページ
                  <% end %>
                </li>
                <li>
                  <%= link_to public_items_path do %>
                    商品一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to public_cart_items_path do %>
                    カート
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_customer_session_path, method: :delete do %>
                    ログアウト
                  <% end %>
                </li>

              <% else %>
                <li>
                  <%= link_to public_about_path do %>
                    About
                  <% end %>
                </li>
                <li>
                  <%= link_to public_items_path do %>
                    商品一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to new_customer_registration_path do %>
                    新規登録
                  <% end %>
                </li>
                <li>
                  <%= link_to new_customer_session_path do %>
                    ログイン
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>